#!/usr/bin/env fish
# Author: David Pätzel


function bupit
    set -l dir "$argv"


    if test -d "$dir"
        set -x BUP_DIR "$dir"/(hostname)


        bup init
        and bup index "/home/$USER"
        and bup save -n (hostname)-home-"$USER" "/home/$USER"
        and bup fsck -g
    else
        echo "Not available: $dir"
        exit 1
    end
end


bupit $argv
