#!/usr/bin/env bash

APROFILE=$(autorandr --detected)

case $APROFILE in
"docked")
	PMONITOR="DP1"
	;;
"mobile")
	PMONITOR="eDP1"
	;;
"n1058")
	PMONITOR="HDMI1"
	;;
"conference")
	PMONITOR="HDMI1"
	;;
*)
	echo "No valid autorandr profile detected!" 1>&2
	exit 1
	;;
esac

sed -i "21s/.*/monitor = $PMONITOR/" ~/.dotfiles/polybar/.config/polybar/config

# Launch polybar

if ! pgrep polybar > /dev/null
then
	echo "Starting polybar in $APROFILE configuration ..."
	polybar --reload top &
else
	echo "Reloading polybar in $APROFILE configuration ..."
fi
