#!/usr/bin/env bash

filename=$(basename -- "$@")
extension="${filename##*.}"
name="${filename%.*}"

if [ ! -e "$filename" ] || [ "$extension" != "tex" ]
then exit 1
fi

shopt -s extglob

rm -rf $name.aux $name.fdb_latexmk $name.fls $name.log $name.nav $name.out $name.snm $name.synctex.gz $name.toc $name.vrb $name.bcf $name.blg
mkdir -p out
mv "$name.pdf" out
