#!/usr/bin/env bash

filename=$(basename -- "$@")
extension="${filename##*.}"
name="${filename%.*}"

if [ ! -e "$filename" ] || [ "$extension" != "tex" ]
then exit 1
fi

shopt -s extglob

rm -rf !(*.pdf|*.tex|out)
mkdir -p out
mv "$name.pdf" out
